## kapacitor image version
## ref: https://hub.docker.com/r/library/kapacitor/tags/
##
image:
  repository: "kapacitor"
  tag: "1.5.2-alpine"
  pullPolicy: "IfNotPresent"

## Specify a service type, defaults to NodePort
## ref: http://kubernetes.io/docs/user-guide/services/
##
service:
  type: ClusterIP

## Persist data to a persistent volume
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  enabled: false
  ## kapacitor data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  accessMode: ReadWriteOnce
  size: 8Gi
  # existingClaim: ""

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  requests:
    memory: 256Mi
    cpu: 0.1
  limits:
    memory: 2Gi
    cpu: 2

## Set the environment variables for kapacitor (or anything else you want to use)
## ref: https://hub.docker.com/_/kapacitor/
## ref: https://docs.influxdata.com/kapacitor/latest/administration/configuration/
##
# Examples below
#
# envVars:
#   KAPACITOR_SLACK_ENABLED: true
#   KAPACITOR_SLACK_URL: "http://slack.com/xxxxx/xxxxx/xxxx/xxxxxxx"
#   KAPACITOR_HTTP_LOG_ENABLED: true
#   KAPACITOR_LOGGING_LEVEL: "INFO"
#
# or, at your terminal, with
#
# helm install --name kapacitor-rls --set influxURL=http://influxurl.com,envVars.KAPACITOR_SLACK_ENABLED=true,envVars.KAPACITOR_SLACK_URL="http://slack.com/xxxxx/xxxxx/xxxx/xxxxxxx" stable/kapacitor
envVars:
  KAPACITOR_CONFIG_OVERRIDE_ENABLE: 'false'
  KAPACITOR_HOSTNAME: kapacitor
  KAPACITOR_HTTP_AUTH_ENABLED: 'false'
  KAPACITOR_HTTP_LOG_ENABLED: 'false'
  KAPACITOR_INFLUXDB_0_DISABLE_SUBSCRIPTIONS: 'false'
  KAPACITOR_INFLUXDB_0_HTTP_PORT: '443'
  KAPACITOR_INFLUXDB_0_NAME: kapacitor
  KAPACITOR_INFLUXDB_0_PASSWORD: influxdbadmin
  KAPACITOR_INFLUXDB_0_SUBSCRIPTION_MODE: server
  KAPACITOR_INFLUXDB_0_SUBSCRIPTION_PROTOCOL: https
  #KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
  KAPACITOR_INFLUXDB_0_USERNAME: admin
  KAPACITOR_LOAD_DIR: /etc/kapacitor/load
  KAPACITOR_LOAD_ENABLED: 'true'
  KAPACITOR_STATS_ENABLED: "true"
  KAPACITOR_STATS_DATABASE: "_kapacitor"

## Set the URL of InfluxDB instance to create subscription on
## ref: https://docs.influxdata.com/kapacitor/v1.1/introduction/getting_started/
##
influxURL: http://influxdb:8086
