## Default values.yaml for Telegraf
## This is a YAML-formatted file.
## ref: https://hub.docker.com/r/library/telegraf/tags/

replicaCount: 1

image:
  repo: "telegraf"
  tag: "1.12-alpine"
  pullPolicy: IfNotPresent

podAnnotations: {}

imagePullSecrets: []

env:
  - name: HOSTNAME
    value: "telegraf-polling-service"

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
resources: {}
  # requests:
  #   memory: 128Mi
  #   cpu: 100m
  # limits:
  #   memory: 128Mi
  #   cpu: 100m

service:
  enabled: false
  type: ClusterIP
## Exposed telegraf configuration
## For full list of possible values see `/docs/all-config-values.yaml` and `/docs/all-config-values.toml`
## ref: https://docs.influxdata.com/telegraf/v1.1/administration/configuration/
config:
  agent:
    interval: "10s"
    round_interval: true
    metric_batch_size: 1000
    metric_buffer_limit: 10000
    collection_jitter: "0s"
    flush_interval: "10s"
    flush_jitter: "0s"
    precision: ""
    debug: false
    quiet: false
    logfile: ""
    hostname: "$HOSTNAME"
    omit_hostname: false
  processors:
    - enum:
        mapping:
          field: "status"
          dest: "status_code"
          value_mappings:
            healthy: 1
            problem: 2
            critical: 3
  outputs:
    - influxdb:
        urls:
          - "http://influxdb:8086"
        database: "demo"
        username: admin
        password: influxdbadmin
  inputs:
  - kubernetes: {}
  - cpu:
      percpu: false
      totalcpu: true
      collect_cpu_time: false
      report_active: true
  - disk:
      ignore_fs:
      - tmpfs
      - devtmpfs
      - devfs
      - iso9660
      - overlay
      - aufs
      - squashfs
  - diskio: {}
  - kernel: {}
  - kernel_vmstat: {}
  - mem: {}
  - netstat: {}
  - processes: {}
  - swap: {}
  - system: {}
